version: '3.8'
services:
  db:
    image: postgres:15
    container_name: imdb-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1204752
      POSTGRES_DB: imdb_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data # 数据持久化到本地